name: PHT

on:
    push:
        branches:
            - main
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        container:
            image: node:20
        steps:
            - uses: actions/checkout@v3
              with:
                node-version: 20
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
            - name: build
              run: npm run build
            - name: Deploy
              run: echo "Deploying!"